
package soap.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebShopService", targetNamespace = "http://soap.services/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebShopService {


    /**
     * 
     * @param arg0
     * @return
     *     returns soap.stub.ShoppingCart
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/getShoppingCartRequest", output = "http://soap.services/WebShopService/getShoppingCartResponse")
    public ShoppingCart getShoppingCart(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/checkoutRequest", output = "http://soap.services/WebShopService/checkoutResponse")
    public String checkout(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.stub.Product
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/getProductRequest", output = "http://soap.services/WebShopService/getProductResponse")
    public Product getProduct(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.stub.ShoppingCart
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/putProductRequest", output = "http://soap.services/WebShopService/putProductResponse")
    public ShoppingCart putProduct(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns soap.stub.StockItem
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/getStockItemRequest", output = "http://soap.services/WebShopService/getStockItemResponse")
    public StockItem getStockItem(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns soap.stub.Stock
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/getStockRequest", output = "http://soap.services/WebShopService/getStockResponse")
    public Stock getStock();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns soap.stub.ShoppingCart
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.services/WebShopService/deleteProductRequest", output = "http://soap.services/WebShopService/deleteProductResponse")
    public ShoppingCart deleteProduct(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
